name: clang-format
on: [push, pull_request, workflow_dispatch]
jobs:
  formatting-check:
    name: Format check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check for C/C++ programs.
      uses: jidicula/clang-format-action@main
      with:
        check-path: 'mays'
