name: clang-tidy-push
on: [push, workflow_dispatch]
jobs:
  static-analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
    - name: Install clang-tidy
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-tidy
    - name: Prepare compile_commands.json
      run: |
        cmake -B ${{github.workspace}}/build
        ln -s ${{github.workspace}}/build/compile_commands.json ${{github.workspace}}
    - name: Run analysis
      run: |
        find mays -name '*.cc' -o -name '*.h' | xargs -P0 -I {} clang-tidy {}
