name: Tests

on: [push, pull_request]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - { compiler: GCC, CC: gcc, CXX: g++, VERSION: 11 }
          - { compiler: Clang, CC: clang, CXX: clang++, VERSION: 13 }

    steps:
    - uses: actions/checkout@v2

    - name: Set up Clang
      if: matrix.compiler.compiler == 'Clang'
      uses: egor-tensin/setup-clang@v1
      with:
        version: ${{ matrix.compiler.VERSION }}
        cc: 1

    - name: Set up GCC
      if: matrix.compiler.compiler == 'GCC'
      uses: egor-tensin/setup-gcc@v1
      with:
        version: ${{ matrix.compiler.VERSION }}
        cc: 1

    - name: Select compiler
      run: |
         echo "CC=${{ matrix.compiler.CC }}-${{ matrix.compiler.VERSION }}" >> $GITHUB_ENV
         echo "CXX=${{ matrix.compiler.CXX }}-${{ matrix.compiler.VERSION }}" >> $GITHUB_ENV

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
