name: Tests

on: [push, pull_request, workflow_dispatch]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build-test:
    name: Tests (${{ matrix.compiler }} C++${{ matrix.std }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [ GCC, Clang ]
        coverage: [ OFF, ON ]
        std: [17, 20]
        exclude:
          - coverage: ON
        include:
          - compiler: Clang
            version: 15
          - compiler: GCC
            version: latest
          - std: 17
            test_with_cxx20: OFF
          - std: 20
            test_with_cxx20: ON
          - compiler: Clang
            std: 20
            version: latest
            test_with_cxx20: ON
            coverage: ON

    steps:
    - uses: actions/checkout@v2

    - name: Set up Clang
      if: matrix.compiler == 'Clang'
      uses: egor-tensin/setup-clang@v1
      with:
        version: ${{ matrix.version }}
        cc: 1

    - name: Set up GCC
      if: matrix.compiler == 'GCC'
      uses: egor-tensin/setup-gcc@v1
      with:
        version: ${{ matrix.version }}
        cc: 1

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCODE_COVERAGE=${{ matrix.coverage }} -DTEST_WITH_CXX20=${{ matrix.test_with_cxx20 }}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --parallel --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Coverage processing seems to be broken when run through ctest
      # run: ctest -C ${{env.BUILD_TYPE}}
      run: ./mays_tests --use-colour=yes

    - name: Process coverage data
      if: matrix.coverage == 'ON'
      working-directory: ${{github.workspace}}/build
      run: |
        llvm-profdata-${{ matrix.version }} merge -sparse default.profraw -o coverage.profdata
        llvm-cov-${{ matrix.version }} show ./mays_tests -instr-profile=coverage.profdata > coverage.txt

    - name: Upload coverage data to Codecov
      uses: codecov/codecov-action@v2
      if: matrix.coverage == 'ON'
      with:
        files: ${{github.workspace}}/build/coverage.txt
